### ISSUE TITLE
Slow down

### ISSUE THREAD

**Issue by szandala** [Ty7ak/ty7ak.github.io#1]
Dobry wieczór,
mógłby Pan nieco spowolnić opady? Odrobinę
Jeszcze mi ktoś na atak epilepsji zejdzie...

**Comment by Ty7ak** [comment]
> Dobry wieczór,
> mógłby Pan nieco spowolnić opady? Odrobinę
> Jeszcze mi ktoś na atak epilepsji zejdzie...

Śnieg został spowolniony. Symulacja powinna teraz lepiej oddawać klimat świąt.

**Comment by szandala** [comment]
Świąt? Chyba Wielkanocnych...
Dawno nie widziałem śniegu an Boże Narodzenie.

Ale jest lepiej, bardziej naturalnie. Dziękuję
